debug

diff --git a/.github/workflows/chart-test.yaml b/.github/workflows/chart-test.yaml
--- a/.github/workflows/chart-test.yaml
+++ b/.github/workflows/chart-test.yaml
@@ -41,7 +41,7 @@ jobs:
         run: |
           ct lint --target-branch main --chart-dirs charts --chart-dirs other-charts
           if [[ $? -ne 0 ]]; then
-            echo "failed=true" >> $GITHUB_OUTPUT
+            echo 'failed=true' >> $GITHUB_OUTPUT
           fi
           echo $?
 
@@ -50,7 +50,7 @@ jobs:
         run: |
           ct lint --target-branch main --all --chart-dirs charts --chart-dirs other-charts
           if [[ $? -ne 0 ]]; then
-            echo "failed=true" >> $GITHUB_OUTPUT
+            echo 'failed=true' >> $GITHUB_OUTPUT
           fi
           echo $?
 
@@ -113,8 +113,9 @@ jobs:
         if: ${{ github.ref != 'refs/heads/main' && steps.list-changed.outputs.changed == 'true' }}
         run: |
           ct install --target-branch main --chart-dirs charts --chart-dirs other-charts
+          echo $?
           if [[ $? -ne 0 ]]; then
-            echo "failed=true" >> $GITHUB_OUTPUT
+            echo 'failed=true' >> $GITHUB_OUTPUT
           fi
           echo $?
 
@@ -125,7 +126,7 @@ jobs:
         run: |
           ct install --target-branch main --all --chart-dirs charts --chart-dirs other-charts
           if [[ $? -ne 0 ]]; then
-            echo "failed=true" >> $GITHUB_OUTPUT
+            echo 'failed=true' >> $GITHUB_OUTPUT
           fi
 
       - name: Notify Slack of chart install failure
